"""Add real-world fields

Revision ID: ac4a6334e20f
Revises: 64b6426ed70e
Create Date: 2026-06-17 15:19:18.986365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4a6334e20f'
down_revision: Union[str, None] = '64b6426ed70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applications', sa.Column('credit_utilization_ratio', sa.Float(), nullable=False, server_default='0.3'))
    op.add_column('loan_applications', sa.Column('previous_defaults', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('loan_applications', sa.Column('monthly_emi', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_applications', 'monthly_emi')
    op.drop_column('loan_applications', 'previous_defaults')
    op.drop_column('loan_applications', 'credit_utilization_ratio')
    # ### end Alembic commands ###
